// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'compress-aggressive'
  | 'compress-balanced'
  | 'compress-menu'
  | 'prefs-attachment-title'
  | 'prefs-auto-close-reader'
  | 'prefs-behavior-title'
  | 'prefs-compress-title'
  | 'prefs-default-preset'
  | 'prefs-gain-10'
  | 'prefs-gain-2'
  | 'prefs-gain-20'
  | 'prefs-gain-threshold'
  | 'prefs-gain-threshold-desc'
  | 'prefs-mode-copy'
  | 'prefs-mode-copy-desc'
  | 'prefs-mode-overwrite'
  | 'prefs-mode-overwrite-desc'
  | 'prefs-preset-aggressive'
  | 'prefs-preset-balanced'
  | 'prefs-show-result'
  | 'startup-begin'
  | 'startup-finish';
